version: "3"

services:
  mongo:
    container_name: mongo-container
    image: mongo:5
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  api:
    container_name: signup-api-container
    build: .
    image: signup-node
    restart: always
    command: yarn debugs
    volumes:
      - ./dist:/usr/src/signup-node/dist
      - ./package.json:/usr/src/signup-node/package.json
    ports:
      - "5353:5353"
      - "9222:9222"
    links:
      - mongo